package lock

import (
	"sync"
)

type call[V any] struct {
	wg  sync.WaitGroup
	val V
	err error
}

// SingleFlightMap is a highly optimized concurrent map.
type SingleFlightMap[K comparable, V any] struct {
	mu    sync.RWMutex
	items map[K]V

	cmu   sync.Mutex
	calls map[K]*call[V]
}

func NewSingleFlightMap[K comparable, V any]() *SingleFlightMap[K, V] {
	return &SingleFlightMap[K, V]{
		items: make(map[K]V),
		calls: make(map[K]*call[V]),
	}
}

// GetOrFill returns the value. If missing, it coordinates a single generator call.
func (m *SingleFlightMap[K, V]) GetOrFill(key K, generator func() (V, error)) (V, error) {
	m.mu.RLock()
	val, ok := m.items[key]
	m.mu.RUnlock()

	if ok {
		return val, nil
	}

	m.cmu.Lock()

	// double check
	m.mu.RLock()
	val, ok = m.items[key]
	m.mu.RUnlock()

	if ok {
		m.cmu.Unlock()

		return val, nil
	}

	if call, inFlight := m.calls[key]; inFlight {
		m.cmu.Unlock()

		call.wg.Wait()

		return call.val, call.err
	}

	c := new(call[V])

	c.wg.Add(1)

	m.calls[key] = c

	m.cmu.Unlock()

	defer func() {
		m.cmu.Lock()
		delete(m.calls, key)
		m.cmu.Unlock()

		c.wg.Done()
	}()

	c.val, c.err = generator()
	if c.err == nil {
		m.mu.Lock()
		m.items[key] = c.val
		m.mu.Unlock()
	}

	return c.val, c.err
}

// Get returns the value if it exists. It does NOT wait for in-flight generations.
func (m *SingleFlightMap[K, V]) Get(key K) (V, bool) {
	m.mu.RLock()
	val, ok := m.items[key]
	m.mu.RUnlock()

	return val, ok
}

// Set forcefully overwrites a key.
func (m *SingleFlightMap[K, V]) Set(key K, val V) {
	m.mu.Lock()
	m.items[key] = val
	m.mu.Unlock()
}

// Delete removes a key from the map.
func (m *SingleFlightMap[K, V]) Delete(key K) {
	m.mu.Lock()
	delete(m.items, key)
	m.mu.Unlock()
}

// GetAndWait returns the value if it exists. If the value is currently
// being generated by another goroutine, it will pause and wait for that
// generation to finish before returning the result.
// If the key is completely missing and not being generated, it returns false.
func (m *SingleFlightMap[K, V]) GetAndWait(key K) (V, bool) {
	m.mu.RLock()
	val, ok := m.items[key]
	m.mu.RUnlock()

	if ok {
		return val, true
	}

	m.cmu.Lock()

	// double check
	m.mu.RLock()
	val, ok = m.items[key]
	m.mu.RUnlock()

	if ok {
		m.cmu.Unlock()

		return val, true
	}

	c, inFlight := m.calls[key]
	if !inFlight {
		m.cmu.Unlock()

		var zero V

		return zero, false
	}

	m.cmu.Unlock()

	c.wg.Wait()

	if c.err != nil {
		var zero V

		return zero, false
	}

	return c.val, true
}
