package lock

import (
	"sync"
	"time"
)

type call[V any] struct {
	wg  sync.WaitGroup
	val V
	err error
}

type item[V any] struct {
	val V
	id  uint64
}

// SingleFlightMap is a highly optimized concurrent map with optional TTLs.
type SingleFlightMap[K comparable, V any] struct {
	mu    sync.RWMutex
	items map[K]item[V]

	seq    uint64
	timers map[K]*time.Timer

	cmu   sync.Mutex
	calls map[K]*call[V]
}

func NewSingleFlightMap[K comparable, V any]() *SingleFlightMap[K, V] {
	return &SingleFlightMap[K, V]{
		items:  make(map[K]item[V]),
		timers: make(map[K]*time.Timer),
		calls:  make(map[K]*call[V]),
	}
}

// Keys returns a slice of all keys currently in the map.
func (m *SingleFlightMap[K, V]) Keys() []K {
	m.mu.RLock()

	keys := make([]K, 0, len(m.items))

	for k := range m.items {
		keys = append(keys, k)
	}

	m.mu.RUnlock()

	return keys
}

// GetOrFill calls GetOrFillWithTTL with a 0 TTL (no expiration).
func (m *SingleFlightMap[K, V]) GetOrFill(key K, generator func() (V, error)) (V, error) {
	return m.GetOrFillWithTTL(key, 0, generator)
}

// GetOrFillWithTTL returns the value. If missing, it coordinates a single generator call.
// If ttl is > 0, the item will be automatically and fully removed from memory after the duration.
func (m *SingleFlightMap[K, V]) GetOrFillWithTTL(key K, ttl time.Duration, generator func() (V, error)) (V, error) {
	m.mu.RLock()
	it, ok := m.items[key]
	m.mu.RUnlock()

	if ok {
		return it.val, nil
	}

	m.cmu.Lock()

	// double check
	m.mu.RLock()
	it, ok = m.items[key]
	m.mu.RUnlock()

	if ok {
		m.cmu.Unlock()

		return it.val, nil
	}

	if call, inFlight := m.calls[key]; inFlight {
		m.cmu.Unlock()

		call.wg.Wait()

		return call.val, call.err
	}

	c := new(call[V])

	c.wg.Add(1)

	m.calls[key] = c

	m.cmu.Unlock()

	defer func() {
		m.cmu.Lock()
		delete(m.calls, key)
		m.cmu.Unlock()

		c.wg.Done()
	}()

	c.val, c.err = generator()
	if c.err == nil {
		m.mu.Lock()

		if freshItem, alreadySet := m.items[key]; alreadySet {
			c.val = freshItem.val
		} else {
			m.seq++

			id := m.seq

			m.items[key] = item[V]{
				val: c.val,
				id:  id,
			}

			if oldTimer, exists := m.timers[key]; exists {
				oldTimer.Stop()
			}

			if ttl > 0 {
				m.timers[key] = time.AfterFunc(ttl, func() {
					m.mu.Lock()

					current, exists := m.items[key]
					if exists && current.id == id {
						delete(m.items, key)
						delete(m.timers, key)
					}

					m.mu.Unlock()
				})
			} else {
				delete(m.timers, key)
			}
		}

		m.mu.Unlock()
	}

	return c.val, c.err
}

// MustGetOrFill calls MustGetOrFillWithTTL with a 0 TTL (no expiration).
func (m *SingleFlightMap[K, V]) MustGetOrFill(key K, generator func() V) V {
	return m.MustGetOrFillWithTTL(key, 0, generator)
}

// MustGetOrFillWithTTL returns the value. If missing, it coordinates a single generator call.
// If ttl is > 0, the item will be automatically and fully removed from memory after the duration.
func (m *SingleFlightMap[K, V]) MustGetOrFillWithTTL(key K, ttl time.Duration, generator func() V) V {
	m.mu.RLock()
	it, ok := m.items[key]
	m.mu.RUnlock()

	if ok {
		return it.val
	}

	val, _ := m.GetOrFillWithTTL(key, ttl, func() (V, error) {
		return generator(), nil
	})

	return val
}

// Get returns the value if it exists. It does NOT wait for in-flight generations.
func (m *SingleFlightMap[K, V]) Get(key K) (V, bool) {
	m.mu.RLock()
	it, ok := m.items[key]
	m.mu.RUnlock()

	return it.val, ok
}

// Set forcefully overwrites a key with no TTL.
func (m *SingleFlightMap[K, V]) Set(key K, val V) {
	m.SetWithTTL(key, val, 0)
}

// SetWithTTL forcefully overwrites a key and applies a TTL.
func (m *SingleFlightMap[K, V]) SetWithTTL(key K, val V, ttl time.Duration) {
	m.mu.Lock()

	m.seq++

	id := m.seq

	m.items[key] = item[V]{
		val: val,
		id:  id,
	}

	if oldTimer, exists := m.timers[key]; exists {
		oldTimer.Stop()
	}

	if ttl > 0 {
		m.timers[key] = time.AfterFunc(ttl, func() {
			m.mu.Lock()

			current, exists := m.items[key]
			if exists && current.id == id {
				delete(m.items, key)
				delete(m.timers, key)
			}

			m.mu.Unlock()
		})
	} else {
		delete(m.timers, key)
	}

	m.mu.Unlock()
}

// Delete removes a key from the map.
func (m *SingleFlightMap[K, V]) Delete(key K) {
	m.mu.Lock()

	delete(m.items, key)

	if t, exists := m.timers[key]; exists {
		t.Stop()

		delete(m.timers, key)
	}

	m.mu.Unlock()
}

// GetAndWait returns the value if it exists. If the value is currently
// being generated by another goroutine, it will pause and wait.
func (m *SingleFlightMap[K, V]) GetAndWait(key K) (V, bool) {
	m.mu.RLock()
	it, ok := m.items[key]
	m.mu.RUnlock()

	if ok {
		return it.val, true
	}

	m.cmu.Lock()

	// double check
	m.mu.RLock()
	it, ok = m.items[key]
	m.mu.RUnlock()

	if ok {
		m.cmu.Unlock()

		return it.val, true
	}

	c, inFlight := m.calls[key]
	if !inFlight {
		m.cmu.Unlock()

		var zero V

		return zero, false
	}

	m.cmu.Unlock()

	c.wg.Wait()

	if c.err != nil {
		var zero V

		return zero, false
	}

	return c.val, true
}
